### ISSUE TITLE
thread_saver: Не удалось получить тред, повтор

### ISSUE THREAD

**Issue by triplenick** [diademoff/2ch#7]
В попытке скачать тред, вылезает:
```
Не удалось получить тред, повтор
Не удалось получить тред, повтор
Не удалось получить тред, повтор
Traceback (most recent call last):
  File "W:\test000\2ch\thread_saver.py", line 31, in get_thread
    thread.update_posts()
  File "W:\test000\2ch\dvach.py", line 198, in update_posts
    self.get_posts(json_posts)
  File "W:\test000\2ch\dvach.py", line 203, in get_posts
    self.unique_posters = int(posts_json[0]['unique_posters'])
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\test000\2ch\thread_saver.py", line 113, in <module>
    thread = get_thread(board, thread_num)
  File "W:\test000\2ch\thread_saver.py", line 35, in get_thread
    time.sleep(5)
```

**usercode_auth** менял на свой, не помогает...

**Comment by diademoff** [comment]
Спасибо за сообщение, api немного поменяли. Последний коммит должен решить проблему.

**Comment by triplenick** [comment]
Да ладно)
Это тебе спасибо за столь ёмкий вклад в специфическом направлении
